gha-runner-scale-set:
  controllerServiceAccount: # Needs to be specified because live discovery doesn't work when applying this chart with Argo instead of Helm
    namespace: arc-systems # Reference here - https://github.com/actions/actions-runner-controller/issues/3043#issuecomment-2502263842
    name: github-arc-runners-controller-gha-rs-controller
  githubConfigUrl: https://github.com/kbntx-org
  githubConfigSecret: github-arc-runners-secret
  maxRunners: 4
  minRunners: 0
  runnerGroup: 'default'
  runnerScaleSetName: nexus-org-runners
  listenerTemplate:
    spec:
      containers:
        - name: listener
  template:
    metadata:
      labels:
        github-job-pod: 'true'
    spec:
      runtimeClassName: sysbox-runc
      hostUsers: false
      containers:
        - name: runner
          image: kbntx/nexus-ci-toolkit:1.5
          command:
            - /home/runner/run.sh
          env:
            - name: DOCKER_HOST
              value: unix:///run/docker.sock
          startupProbe:
            exec:
              command: ['docker', 'info']
            initialDelaySeconds: 0
            failureThreshold: 24
            periodSeconds: 5
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: docker-sock
              mountPath: /run
        - name: dind
          image: docker:29.7.2-dind
          args:
            - --group=123
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: docker-sock
              mountPath: /run
      volumes:
        - name: work
          emptyDir: {}
        - name: docker-sock
          emptyDir: {}
      nodeSelector:
        pool: ci-runners
      tolerations:
        - key: 'ci-runners'
          operator: 'Equal'
          value: 'true'
          effect: 'NoSchedule'
