injectWorkspacePackages: true
engineStrict: true
minimumReleaseAgeStrict: true

packages:
  - 'apps/portfolio'

minimumReleaseAgeExclude:
  - '@nx/angular@22.7.3'
  - '@nx/devkit@22.7.3'
  - '@nx/eslint-plugin@22.7.3'
  - '@nx/eslint@22.7.3'
  - '@nx/js@22.7.3'
  - '@nx/module-federation@22.7.3'
  - '@nx/nx-darwin-arm64@22.7.3'
  - '@nx/nx-darwin-x64@22.7.3'
  - '@nx/nx-freebsd-x64@22.7.3'
  - '@nx/nx-linux-arm-gnueabihf@22.7.3'
  - '@nx/nx-linux-arm64-gnu@22.7.3'
  - '@nx/nx-linux-arm64-musl@22.7.3'
  - '@nx/nx-linux-x64-gnu@22.7.3'
  - '@nx/nx-linux-x64-musl@22.7.3'
  - '@nx/nx-win32-arm64-msvc@22.7.3'
  - '@nx/nx-win32-x64-msvc@22.7.3'
  - '@nx/rspack@22.7.3'
  - '@nx/web@22.7.3'
  - '@nx/webpack@22.7.3'
  - '@nx/workspace@22.7.3'
  - nx@22.7.3

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  nx: false
