root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/kiln ./cmd"
  bin = "./tmp/kiln"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = "500ms"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
