apiVersion: cloudflare.kbntx.com/v1alpha1
kind: Tunnel
metadata:
  name: k3s
spec:
  routes:
    - 10.43.0.0/16
    - 10.42.0.0/16
  ingress:
    - hostname: kbntx.com
      service: https://traefik-ingress.traefik-ingress.svc.cluster.local
      originRequest:
        matchSNItoHost: true
    - hostname: "*.kbntx.com"
      service: https://traefik-ingress.traefik-ingress.svc.cluster.local
      originRequest:
        matchSNItoHost: true
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: k3s-tunnel-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: k3s-tunnel
