apiVersion: cloudflare.kbntx.com/v1alpha1
kind: Tunnel
metadata:
  name: k3s
spec:
  routes:
    - 10.43.0.0/16
    - 10.42.0.0/16
  ingress:
    - hostname: kbntx.com
      service: https://traefik-ingress.traefik-ingress.svc.cluster.local
      originRequest:
        matchSNItoHost: true
    - hostname: "*.kbntx.com"
      service: https://traefik-ingress.traefik-ingress.svc.cluster.local
      originRequest:
        matchSNItoHost: true
  podDisruptionBudget:
    minAvailable: 1
