apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingress
spec:
  routes:
    - match: Host(`{{ .Values.global.domain }}`)
      kind: Rule
      services:
        - name: argocd-server
          port: http
