apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-auth
  labels:
    app: supabase-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-auth
  template:
    metadata:
      labels:
        app: supabase-auth
    spec:
      containers:
        - name: auth
          image: supabase/gotrue:v2.177.0
          ports:
            - containerPort: 9999
          env:
            - name: GOTRUE_API_HOST
              value: "0.0.0.0"
            - name: GOTRUE_API_PORT
              value: "9999"
            - name: API_EXTERNAL_URL
              value: "https://api-supabase.kbntx.com"
            - name: GOTRUE_DB_DRIVER
              value: "postgres"
            - name: GOTRUE_DB_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: dbUrlAuth
            - name: GOTRUE_SITE_URL
              value: "https://supabase.kbntx.com"
            - name: GOTRUE_URI_ALLOW_LIST
              value: ""
            - name: GOTRUE_DISABLE_SIGNUP
              value: "false"
            - name: GOTRUE_JWT_ADMIN_ROLES
              value: "service_role"
            - name: GOTRUE_JWT_AUD
              value: "authenticated"
            - name: GOTRUE_JWT_DEFAULT_GROUP_NAME
              value: "authenticated"
            - name: GOTRUE_JWT_EXP
              value: "3600"
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: jwtSecret

            # Email config
            - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
              value: "false"
            # - name: GOTRUE_MAILER_AUTOCONFIRM
            #   value: "true"
            # - name: GOTRUE_SMTP_ADMIN_EMAIL
            #   valueFrom:
            #     secretKeyRef:
            #       name: supabase-secrets
            #       key: SMTP_ADMIN_EMAIL
            # - name: GOTRUE_SMTP_HOST
            #   valueFrom:
            #     secretKeyRef:
            #       name: supabase-secrets
            #       key: SMTP_HOST
            # - name: GOTRUE_SMTP_PORT
            #   valueFrom:
            #     secretKeyRef:
            #       name: supabase-secrets
            #       key: SMTP_PORT
            # - name: GOTRUE_SMTP_USER
            #   valueFrom:
            #     secretKeyRef:
            #       name: supabase-secrets
            #       key: SMTP_USER
            # - name: GOTRUE_SMTP_PASS
            #   valueFrom:
            #     secretKeyRef:
            #       name: supabase-secrets
            #       key: SMTP_PASS
            # - name: GOTRUE_SMTP_SENDER_NAME
            #   value: "Supabase Auth"

          readinessProbe:
            httpGet:
              path: /health
              port: 9999
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-auth
  labels:
    app: supabase-auth
spec:
  selector:
    app: supabase-auth
  ports:
    - port: 9999
      targetPort: 9999
      name: http
