apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-realtime
  labels:
    app: supabase-realtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-realtime
  template:
    metadata:
      labels:
        app: supabase-realtime
    spec:
      containers:
        - name: realtime
          image: supabase/realtime:v2.34.47
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              value: supabase-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: dbName
            - name: DB_AFTER_CONNECT_QUERY
              value: "SET search_path TO _realtime"
            - name: DB_ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: dbEncryptionKey
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: jwtSecret
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: secretKeyBase
            - name: APP_NAME
              value: "realtime"
            - name: SEED_SELF_HOST
              value: "true"
            - name: RUN_JANITOR
              value: "true"
            - name: RLIMIT_NOFILE
              value: "10000"
            - name: DNS_NODES
              value:  "''"
            - name: ERL_AFLAGS
              value: -proto_dist inet_tcp
          readinessProbe:
            httpGet:
              path: /api/tenants/realtime-dev/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: supabase-realtime
  labels:
    app: supabase-realtime
spec:
  selector:
    app: supabase-realtime
  ports:
    - port: 4000
      targetPort: 4000
      name: http
