apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ingress-controller-secret
type: Opaque
stringData:
  CF_API_TOKEN: {{ .Values.cloudflare.apiToken | quote }}
  CF_ACCOUNT_ID: {{ .Values.cloudflare.accountId | quote }}
  CF_TUNNEL_ID: {{ .Values.cloudflare.tunnelId | quote }}
  CF_ZONE_ID: {{ .Values.cloudflare.zoneId | quote }}
