name: Docker build and push
description: Build, and optionally push, Docker images using the Docker CLI against the runner's dind sidecar
inputs:
  tag:
    description: 'Image tag'
    required: true
  file:
    description: 'Path to Dockerfile'
    required: true
  context:
    description: 'Build context path'
    required: true
  push:
    description: 'Whether to push the built image to the registry'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Build (and push) with docker buildx
      shell: bash
      run: |
        buildArgs=(--file "${{ inputs.file }}" --tag "${{ inputs.tag }}")
        if [ "${{ inputs.push }}" = "true" ]; then
          buildArgs+=(--output type=registry,oci-mediatypes=true,compression=zstd,force-compression=true)
        fi
        docker buildx build "${buildArgs[@]}" "${{ inputs.context }}"
