---
plugin: hetzner.hcloud.hcloud
strict: true
api_token: '{{ hcloud_token }}'
connect_with: private_ipv4
network: 'main-vpc'
label_selector: 'cluster-name=nexus'

compose:
  private_ipv4: hcloud_private_ipv4

groups:
  k3s_server: "hcloud_labels.get('type') == 'control-plane' and hcloud_labels.get('karpenter.sh/managed-by') != 'karpenter'"
  k3s_worker: "hcloud_labels.get('type') == 'worker' and hcloud_labels.get('karpenter.sh/managed-by') != 'karpenter'"
