apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-secret-sa
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: karpenter-secret-store
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso
          serviceAccountRef:
            name: karpenter-secret-sa
            audiences:
              - vault
      path: platform
      server: https://vault.kbntx.com
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: karpenter-secret-store
    kind: SecretStore
  target:
    name: karpenter-secret
  dataFrom:
    - extract:
        key: karpenter
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karpenter-user-data
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: karpenter-secret-store
    kind: SecretStore
  target:
    name: karpenter-user-data
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        userData: |
          #cloud-config
          write_files:
            - path: /etc/rancher/k3s/config.yaml
              owner: root:root
              permissions: '0600'
              content: |
                token: {{ `{{ .agentToken }}` }}
                server: "https://{{ .Values.cloudInit.k3sServerURL }}:6443"
                kubelet-arg:
                  - "cloud-provider=external"
          runcmd:
            - echo "node-name: $(hostname)" >> /etc/rancher/k3s/config.yaml
            - echo "node-ip: $(ip -4 addr show enp7s0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')" >> /etc/rancher/k3s/config.yaml
            - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ .Values.cloudInit.k3sVersion }} sh -s - agent
  dataFrom:
    - extract:
        key: karpenter
