apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
        - name: mongo-permissions
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              cp /etc/mongodb-key-temp/mongoDbKey /var/lib/mongoKey/mongo.key
              chown -R 999:999 /var/lib/mongoKey
              chmod 400 /var/lib/mongoKey/mongo.key
          volumeMounts:
            - name: mongodb-key-temp
              mountPath: /etc/mongodb-key-temp
            - name: mongodb-key-storage
              mountPath: /var/lib/mongoKey
      volumes:
        - name: mongodb-key-temp
          secret:
            secretName: appsmith-secrets
            items:
              - key: mongoDbKey
                path: mongoDbKey
        - name: mongodb-key-storage
          emptyDir: {}
      containers:
        - name: mongodb
          image: mongo:8.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: mongoDbUser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: mongoDbPassword
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: mongoDbName
          args:
            - --replSet
            - rs0
            - --keyFile
            - /var/lib/mongoKey/mongo.key
            - --bind_ip_all
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-key-storage
              mountPath: /var/lib/mongoKey
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
