apiVersion: v1
kind: ServiceAccount
metadata:
  name: appsmith-secret-sa
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: appsmith-secret-store
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: appsmith
          serviceAccountRef:
            name: appsmith-secret-sa
            audiences:
              - vault
      path: platform
      server: https://vault.kbntx.com
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appsmith-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: appsmith-secret-store
    kind: SecretStore
  target:
    name: appsmith-secret
  dataFrom:
    - extract:
        key: appsmith
