argocd-apps:
  applications:
    traefik-ingress:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/traefik
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: traefik-ingress
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    argocd:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/argocd
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    external-secrets:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/external-secrets
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: external-secrets
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    cloudflared:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/cloudflared
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: cloudflare
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    hetzner-cloud-controller:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/hetzner-cloud-controller
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    monitoring:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/services/monitoring
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    github-arc-runners-controller:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/github-arc-runners/controller
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: arc-systems
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    github-arc-runners:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/github-arc-runners/runners
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: arc-runners
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    system-upgrade-controller:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/kubernetes/upgrades/system-upgrade-controller
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: system-upgrade
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    k3s-upgrades:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: platform/core/kubernetes/upgrades/plans
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: system-upgrade
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    documentation:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: docs/helm
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: documentation
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

    portfolio:
      project: default
      source:
        repoURL: https://github.com/kbntx-org/nexus.git
        path: apps/portfolio/chart
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: portfolio
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
