name: vault

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
    restart: always
    volumes:
      - vault-logs:/vault/logs:rw
    command: server
    cap_add:
      - IPC_LOCK

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${VAULT_POSTGRES_DB}
      POSTGRES_USER: ${VAULT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${VAULT_POSTGRES_PASSWORD}

  cloudflared:
    image: cloudflare/cloudflared:2025.11.1
    restart: always
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run

volumes:
  vault-logs:
  postgres_data:
