dashboardHost: traefik.kbntx.com

internalWebPort: 8010
internalSecurePort: 8011
internalServiceClusterIP: 10.43.216.131

traefik:
  ingressClass:
    isDefaultClass: true
    enabled: true
    name: traefik
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: false

  ports:
    web: null
    websecure:
      forwardedHeaders:
        insecure: false
        trustedIPs: ['10.42.0.0/16']
      expose:
        default: true
    internal-web:
      asDefault: true
      port: 8010
      expose:
        default: false
      http:
        redirections:
          entryPoint:
            to: internal-secure
            scheme: https
            permanent: true
    internal-secure:
      asDefault: true
      port: 8011
      expose:
        default: false
      exposedPort: 443

  additionalArguments:
    - '--api.insecure=true'

  service:
    spec:
      type: ClusterIP

  deployment:
    replicas: 2

  log:
    format: json

  accessLog:
    enabled: true
    format: json
    fields:
      headers:
        defaultMode: drop
        names:
          Referer: keep
          User-Agent: keep
          X-Forwarded-For: keep
          CF-IPCountry: keep
