internalWebPort: 8010
internalSecurePort: 8011
internalServiceClusterIP: 10.43.216.131

traefik:
  ports:
    internal-web:
      asDefault: true
      port: 8010
      expose:
        default: false
      http:
        redirections:
          entryPoint:
            to: internal-secure
            scheme: https
            permanent: true
    internal-secure:
      asDefault: true
      port: 8011
      expose:
        default: false
      exposedPort: 443
