dashboardHost: traefik.kbntx.com

certificate:
  enabled: true

traefik:
  ingressClass:
    isDefaultClass: true
    enabled: true
    name: traefik
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: false

  ports:
    web: null
    websecure:
      forwardedHeaders:
        insecure: false
        trustedIPs: ['10.42.0.0/16']
      expose:
        default: true

  service:
    spec:
      type: ClusterIP

  deployment:
    replicas: 2

  log:
    format: json

  accessLog:
    enabled: true
    format: json
    fields:
      headers:
        defaultMode: drop
        names:
          Referer: keep
          User-Agent: keep
          X-Forwarded-For: keep
          CF-IPCountry: keep
