traefik:
  ingressClass:
    isDefaultClass: true
    enabled: true
    name: traefik
  providers:
    kubernetesCRD:
      enabled: false
    kubernetesIngress:
      enabled: true

  ports:
    web:
      forwardedHeaders:
        insecure: false
        trustedIPs: ['10.42.0.0/16']
      expose:
        default: true
      http:
        encodedCharacters:
          allowEncodedSlash: true
          allowEncodedBackSlash: true
          allowEncodedNullCharacter: true
          allowEncodedSemicolon: true
          allowEncodedPercent: true
          allowEncodedQuestionMark: true
          allowEncodedHash: true
    websecure:
      expose:
        default: false

  additionalArguments:
    - '--api.insecure=true'

  service:
    type: ClusterIP

  deployment:
    replicas: 2

  logs:
    general:
      format: json
      level: DEBUG
    access:
      enabled: true
      format: json
      fields:
        headers:
          defaultMode: drop
          names:
            Referer: keep
            User-Agent: keep
            X-Forwarded-For: keep
            CF-IPCountry: keep
