image:
  repository: n8nio/n8n
  tag: 2.36.2

internalIngressTarget: 10.43.216.131

certificate:
  enabled: true

postgresCluster:
  storageClass: hcloud-volumes

backup:
  enabled: true
  destinationPath: s3://nexus-database-backups/n8n-cnpg
  endpointURL: https://2bde0126da63a3a9c94029d14ea380db.eu.r2.cloudflarestorage.com
