hubbleHost: hubble.kbntx.com
internalIngressTarget: 10.43.216.131

certificate:
  enabled: true

cilium:
  kubeProxyReplacement: true
  k8sServiceHost: nexus-control-plane.kbntx.com
  k8sServicePort: 6443
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList:
        - 10.42.0.0/16
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: false
