apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app: homepage
data:
  bookmarks.yaml: ''
  custom.css: |
    #revalidate {
      display: none;
    }
  custom.js: ''
  docker.yaml: ''
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Quick:
        - Github:
            icon: 'si-github-#000000'
            href: https://github.com/kbntx-org/nexus
        - Grafana:
            icon: grafana.svg
            href: https://grafana.kbntx.com
        - ArgoCD:
            icon: argo-cd.svg
            href: https://argocd.kbntx.com
        - Cloudflare:
            icon: cloudflare.svg
            href: https://dash.cloudflare.com/
        - Hetzner:
            icon: hetzner-h.svg
            href: https://console.hetzner.com
        - Appsmith:
            icon: 'si-appsmith-#F38020'
            href: https://nexus-public-statics.nbg1.your-objectstorage.com/images/appsmith-logo.png
        - S3 Client:
            icon: https://nexus-public-statics.nbg1.your-objectstorage.com/images/s3-logo.svg
            href: https://appsmith.kbntx.com/app/s3-statics-client/page1-691860ad613acd5b6ba7e634
    - Calendar:
        - Calendar:
            widget:
              type: calendar
              firstDayInWeek: monday
              view: monthly
              maxEvents: 10
              showTime: true
  settings.yaml: |
    title: Homepage
    headerStyle: boxed
    background:
      image: https://nbg1.your-objectstorage.com/nexus-public-statics/images/wano-kuni.jpeg
      brightness: 50
    theme: dark
    color: slate
    useEqualHeights: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    hideVersion: true
    layout:
      Quick:
        header: false
        style: column
      Calendar:
        header: false
        style: column
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
        focus: false
        showSearchSuggestions: true
    - openmeteo:
        label: Current
        timezone: Europe/London
        units: metric
        cache: 5
        format:
          maximumFractionDigits: 1
    - datetime:
      text_size: md
      format:
        timeStyle: medium
    - kubernetes:
        cluster:
          show: false
          cpu: false
          memory: false
          showLabel: false
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
