kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: hcloud-volumes
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi

  grafana:
    envValueFrom:
      POSTGRES_USER:
        secretKeyRef:
          name: postgres-credentials
          key: username
      POSTGRES_PASSWORD:
        secretKeyRef:
          name: postgres-credentials
          key: password
    grafana.ini:
      server:
        domain: grafana.kbntx.com
        root_url: 'https://%(domain)s/'
      auth:
        disable_login: true
        disable_login_form: true
      database:
        type: postgres
        host: postgres:5432
        name: grafana
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        ssl_mode: disable

    persistence:
      enabled: false
    sidecar:
      dashboards:
        provider:
          allowUiUpdates: true

loki:
  global:
    extraArgs:
      - -config.expand-env=true
    extraEnv:
      - name: S3_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: s3-loki-credentials
            key: accessKeyId
      - name: S3_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3-loki-credentials
            key: secretAccessKey
      - name: S3_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: s3-loki-credentials
            key: endpoint
      - name: CHUNKS_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: s3-loki-credentials
            key: bucketName
  loki:
    schemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    ingester:
      chunk_encoding: snappy
    auth_enabled: false
    tracing:
      enabled: true
    querier:
      max_concurrent: 4
    storage:
      type: s3
      bucketNames:
        chunks: ${CHUNKS_BUCKET_NAME}
      s3:
        endpoint: ${S3_ENDPOINT}
        region: eu-central-1
        secretAccessKey: ${S3_SECRET_ACCESS_KEY}
        accessKeyId: ${S3_ACCESS_KEY_ID}
        s3ForcePathStyle: false
        insecure: false

  deploymentMode: SimpleScalable
  backend:
    replicas: 3
  read:
    replicas: 3
  write:
    replicas: 3
  minio:
    enabled: false
  ruler:
    enabled: false
