apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: monitoring-ingress
spec:
  routes:
    - match: Host(`{{ .Values.ingress.grafanaHost }}`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80
    - match: Host(`{{ .Values.ingress.prometheusHost }}`)
      kind: Rule
      services:
        - name: prometheus-operated
          port: 9090
