apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-secret-sa
automountServiceAccountToken: false
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: monitoring-secret-store
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: monitoring
          serviceAccountRef:
            name: monitoring-secret-sa
            audiences:
              - vault
      path: platform
      server: https://vault.kbntx.com
      version: v2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: monitoring-secret-store
    kind: SecretStore
  target:
    name: monitoring-secret
  dataFrom:
    - extract:
        key: monitoring
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secret-user-credentials
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: monitoring-secret-store
    kind: SecretStore
  target:
    name: monitoring-secret-user-credentials
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ `{{ .postgresUser }}` }}"
        password: "{{ `{{ .postgresPassword }}` }}"
  dataFrom:
    - extract:
        key: monitoring
