apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflare-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudflare-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudflare-controller
subjects:
  - kind: ServiceAccount
    name: cloudflare-controller
    namespace: {{ .Release.Namespace }}
