---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflare-controller
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.kbntx.com
  resources:
  - accessapplications
  - accesspolicies
  - tunnels
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.kbntx.com
  resources:
  - accessapplications/finalizers
  - accesspolicies/finalizers
  - tunnels/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.kbntx.com
  resources:
  - accessapplications/status
  - accesspolicies/status
  - tunnels/status
  verbs:
  - get
  - patch
  - update
