---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudflare-controller
rules:
- apiGroups:
  - cloudflare.kbntx.com
  resources:
  - accessapplications
  - accesspolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudflare.kbntx.com
  resources:
  - accessapplications/finalizers
  - accesspolicies/finalizers
  verbs:
  - update
- apiGroups:
  - cloudflare.kbntx.com
  resources:
  - accessapplications/status
  - accesspolicies/status
  verbs:
  - get
  - patch
  - update
