apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appsmith-ingress
spec:
  rules:
    - host: appsmith.kbntx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appsmith-service
                port:
                  name: appsmith
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: appsmith
spec:
  serviceName: appsmith-service
  replicas: 1
  selector:
    matchLabels:
      app: appsmith
  template:
    metadata:
      labels:
        app: appsmith
    spec:
      containers:
        - name: appsmith
          image: appsmith/appsmith-ce:v1.89
          ports:
            - containerPort: 80
          env:
            - name: APPSMITH_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: mongoDbUrl
            - name: APPSMITH_REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: redisDbUrl
            - name: APPSMITH_KEYCLOAK_DB_URL
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: keycloakDbUrl
            - name: APPSMITH_ENCRYPTION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: encryptionPassword
            - name: APPSMITH_ENCRYPTION_SALT
              valueFrom:
                secretKeyRef:
                  name: appsmith-secrets
                  key: encryptionSalt
            - name: APPSMITH_DISABLE_TELEMETRY
              value: "true"
            - name: APPSMITH_CLOUD_SERVICES_BASE_URL
              value: ""
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: appsmith-service
spec:
  selector:
    app: appsmith
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP

