apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appsmith-ingress
spec:
  rules:
    - host: appsmith.kbntx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appsmith
                port:
                  name: appsmith
