image:
  repository: kbntx/kiln
  tag: latest
internalIngressTarget: 10.43.216.131
containerPort: 8080
replicas: 2
healthProbes: true
ingressHosts:
  - kiln.kbntx.com
deploymentStrategy: RollingUpdate

devMode: false
frontend:
  image:
    repository: kbntx/kiln-client
    tag: latest
  containerPort: 5173

certificate:
  enabled: true
