site_name: Nexus documentation
repo_name: kbntx-org/nexus
repo_url: https://github.com/kbntx-org/nexus
site_url: https://docs.kbntx.com

docs_dir: src

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

theme:
  name: material
  logo: https://fsn1.your-objectstorage.com/nexus-public-statics/images/kt-logo.jpg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - search.suggest

  palette:
    - media: '(prefers-color-scheme)'
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - awesome-nav
  - glightbox

extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js

extra_css:
  - assets/extra.css

watch:
  - src
  - mkdocs.yml
