site_name: Nexus documentation
repo_name: kbntx/nexus
repo_url: https://github.com/kbntx/nexus
site_url: https://docs.kbntx.com

docs_dir: src

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: https://nexus-public-assets.kbntx.com/images/kt-logo.jpg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - content.code.copy

  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - awesome-nav
  - glightbox

extra_css:
  - assets/extra.css

watch:
  - src
  - mkdocs.yml
