site_name: Nexus documentation
repo_name: kbntx-org/nexus
repo_url: https://github.com/kbntx-org/nexus
site_url: https://docs.kbntx.com

docs_dir: src

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: https://fsn1.your-objectstorage.com/nexus-public-statics/images/kt-logo.jpg
  features:
    - tabs
    - instant
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - content.code.copy

  palette:
    - scheme: slate
      primary: black
      accent: indigo

plugins:
  - search
  - awesome-nav
  - glightbox

extra_css:
  - assets/extra.css

watch:
  - src
  - mkdocs.yml
