#cloud-config
ssh_pwauth: false

users:
  - name: engineer
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true

write_files:
  - path: /etc/ssh/cloudflare-access-ca.pub
    owner: root:root
    permissions: '0644'
    content: |
      ${cloudflare_access_ssh_ca_public_key}

  - path: /etc/ssh/sshd_config.d/disable-root.conf
    owner: root:root
    permissions: '0644'
    content: |
      PermitRootLogin no

  - path: /etc/ssh/sshd_config.d/cloudflare-access.conf
    owner: root:root
    permissions: '0644'
    content: |
      TrustedUserCAKeys /etc/ssh/cloudflare-access-ca.pub
  %{ if docker_hub_username != "" && docker_hub_password != "" }
  - path: /etc/rancher/k3s/registries.yaml
    content: |
      configs:
        "docker.io":
          auth:
            username: ${docker_hub_username}
            password: ${docker_hub_password}
    owner: root:root
    permissions: '0600'
  %{ endif }

runcmd:
  - ufw disable
  - passwd -l root
  - chage -E -1 -M -1 -I -1 -m 0 root
  - systemctl restart ssh
  %{ if type == "control-plane" }
  - |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.33.3+k3s1 sh -s - server \
      --cluster-init \
      --disable-cloud-controller \
      --disable local-storage \
      --node-name="$(hostname -f)" \
      --flannel-iface=enp7s0 \
      --kubelet-arg="cloud-provider=external" \
      --secrets-encryption \
      --disable=traefik \
      --disable=servicelb \
      --node-taint="node-role.kubernetes.io/control-plane=true:NoSchedule" \
      --node-label="node.kubernetes.io/exclude-from-external-load-balancers=true" \
      --token=${cluster_token}
  %{ else }
  - |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.33.3+k3s1 sh -s - agent \
    --server "https://${server_address}:6443" \
    --node-name="$(hostname -f)" \
    --flannel-iface=enp7s0 \
    --kubelet-arg="cloud-provider=external" \
    %{ for label_key, label_value in labels ~}
    --node-label="${label_key}=${label_value}" \
    %{ endfor ~}
    %{ for taint in taints ~}
    --node-taint="${taint.key}=${taint.value}:${taint.effect}" \
    %{ endfor ~}
    --token=${cluster_token}
  %{ endif }
