FROM node:22-alpine

RUN npm install -g pnpm@10.14.0

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN pnpm install --frozen-lockfile

COPY nx.json tsconfig.base.json ./
COPY apps/portfolio ./apps/portfolio

EXPOSE 4200

CMD ["pnpm", "nx", "run", "portfolio:serve", "--host=0.0.0.0", "--poll=2000"]
