apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-postgres
spec:
  serviceName: n8n-postgres
  replicas: 1
  selector:
    matchLabels:
      app: n8n-postgres
  template:
    metadata:
      labels:
        app: n8n-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: postgresDatabase
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: postgresUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: postgresPassword
          volumeMounts:
            - name: n8n-postgres-data
              mountPath: /var/lib/postgresql
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: n8n-postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 15Gi
---
apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres
  labels:
    app: n8n-postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: n8n-postgres
