name: Checks main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    name: Lint & Format
    uses: ./.github/workflows/lint-and-format-main.yaml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/test-main.yml
    secrets: inherit

  deploy-portfolio:
    name: Deploy Portfolio
    needs: [lint-and-format, test]
    uses: ./.github/workflows/deploy-portfolio.yml
    secrets: inherit

  deploy-documentation:
    name: Deploy Documentation
    needs: [lint-and-format, test]
    uses: ./.github/workflows/deploy-documentation.yml
    secrets: inherit
