name: Checks main

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  affected:
    name: Affected
    uses: ./.github/workflows/compute-affected.yml
    secrets: inherit

  lint-and-format:
    name: Lint & Format
    uses: ./.github/workflows/lint-and-format-main.yaml
    secrets: inherit

  test:
    name: Test
    uses: ./.github/workflows/test-main.yml
    secrets: inherit

  deploy-portfolio:
    name: Deploy Portfolio
    needs: [affected, lint-and-format, test]
    if: contains(fromJSON(needs.affected.outputs.deploy_targets), 'portfolio')
    uses: ./.github/workflows/deploy-portfolio.yml
    secrets: inherit
    with:
      image_tag: ${{ github.sha }}

  deploy-documentation:
    name: Deploy Documentation
    needs: [affected, lint-and-format, test]
    if: contains(fromJSON(needs.affected.outputs.deploy_targets), 'documentation')
    uses: ./.github/workflows/deploy-documentation.yml
    secrets: inherit
    with:
      image_tag: ${{ github.sha }}

  deploy-bastion:
    name: Deploy Bastion
    needs: [affected, lint-and-format, test]
    if: contains(fromJSON(needs.affected.outputs.deploy_targets), 'bastion')
    uses: ./.github/workflows/deploy-bastion.yml
    secrets: inherit
