name: Deploy documentation

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Image tag to build and deploy'
        required: true
        type: string

concurrency:
  group: deploy-documentation

jobs:
  build-and-deploy:
    runs-on: nexus-runners
    container:
      image: kbntx/nexus-ci-toolkit:1.0
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: ./.github/actions/buildkit-and-push
        with:
          context: docs
          file: docs/Dockerfile
          tag: kbntx/documentation:${{ inputs.image_tag }}

      - name: Deploy
        env:
          ARGOCD_SERVER: argocd.kbntx.com
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_OPTS: '--grpc-web'
        run: |
          argocd app set documentation -p image.tag=${{ inputs.image_tag }}
          argocd app sync documentation --prune
          argocd app wait documentation --sync --health --operation --timeout 500
