name: Deploy Portfolio

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-portfolio

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build portfolio frontend
        run: pnpm nx build portfolio-frontend --configuration=production

      # Github pages does not support wildcard routing
      - name: Copy index.html to 404.html
        run: cp ./dist/apps/portfolio/frontend/browser/index.html ./dist/apps/portfolio/frontend/browser/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/apps/portfolio/frontend/browser

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
