name: Deploy Vault
on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: deploy-vault

jobs:
  deploy:
    name: Deploy Vault
    runs-on: nexus-runners
    container:
      image: kbntx/nexus-ci-toolkit:1.0
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace environment variables in config
        env:
          VAULT_POSTGRES_CONNECTION_URI: postgres://${{ secrets.VAULT_POSTGRES_USER }}:${{ secrets.VAULT_POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.VAULT_POSTGRES_DB }}
        run: |
          envsubst < platform/core/vault/deploy/config/config.hcl > platform/core/vault/deploy/config/config.hcl.tmp && mv platform/core/vault/deploy/config/config.hcl.tmp platform/core/vault/deploy/config/config.hcl

      - name: Deploy
        uses: ./.github/actions/deploy-with-compose
        env:
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.VAULT_CLOUDFLARE_TUNNEL_TOKEN }}
          VAULT_POSTGRES_DB: ${{ secrets.VAULT_POSTGRES_DB }}
          VAULT_POSTGRES_USER: ${{ secrets.VAULT_POSTGRES_USER }}
          VAULT_POSTGRES_PASSWORD: ${{ secrets.VAULT_POSTGRES_PASSWORD }}
        with:
          user: ci
          server: '10.0.0.3'
          ssh-key: ${{ secrets.NEXUS_CI_PRIVATE_SSH_KEY }}
          ssh-known-hosts: ${{ secrets.VAULT_KNOWN_HOSTS }}
          files: >
            platform/core/vault/deploy/docker-compose.yml
