name: Deploy documentation

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: deploy-documentation

jobs:
  build-and-deploy:
    runs-on: nexus-runners
    container:
      image: kbntx/nexus-ci-toolkit:1.0
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: ./.github/actions/buildkit-and-push
        with:
          context: .
          file: apps/documentation/Dockerfile
          tag: kbntx/documentation:latest

      - name: Deploy
        env:
          ARGOCD_SERVER: argocd.kbntx.com
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
          ARGOCD_OPTS: '--grpc-web'
        run: |
          echo hello1
          argocd app sync documentation --prune
          echo hello2
          argocd app wait documentation --sync --health --operation --timeout 500
          echo hello3
          argocd app actions run documentation restart --kind Deployment --resource-name documentation --namespace documentation
          echo hello4
