name: Lint & Format main

on:
  workflow_call:

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: nexus-runners
    container:
      image: kbntx/nexus-ci-toolkit:1.0
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pnpm install
        shell: bash

      - name: Check formatting
        run: pnpm nx format:check --all
        shell: bash

      - name: Lint
        run: |
          pnpm nx run-many --target lint --all --parallel
        shell: bash
