name: Test

on:
  workflow_call:
    inputs:
      test_projects_csv:
        description: 'Comma-delimited list of affected projects with a test target'
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: nexus-org-runners
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Test
        run: pnpm nx run-many --target=test --projects="${{ inputs.test_projects_csv }}" --parallel --outputStyle=stream
        shell: bash
