name: Upload code source
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: upload-code-source

jobs:
  upload:
    name: Upload code source
    runs-on: nexus-runners
    container:
      image: kbntx/nexus-ci-toolkit:1.0
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download code source
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/kbntx-org/nexus/zipball/main > code-source.zip

      - name: Upload code source to S3
        env:
          S3_ENDPOINT_URL: ${{ secrets.HETZNER_S3_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.HETZNER_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HETZNER_S3_SECRET_ACCESS_KEY }}
        run: |
          s5cmd cp code-source.zip s3://nexus-public-statics/code-sources/nexus.zip
