name: bastion

services:
  cloudflared:
    image: cloudflare/cloudflared:2025.11.1
    restart: always
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
